"""Interactive setup wizard: so-ops init."""

from __future__ import annotations

import json
import os
import ssl
import sys
import urllib.request
from pathlib import Path


def _ask(prompt: str, default: str = "") -> str:
    """Prompt for input with optional default."""
    if default:
        val = input(f"{prompt} [{default}]: ").strip()
        return val if val else default
    while True:
        val = input(f"{prompt}: ").strip()
        if val:
            return val


def _ask_yn(prompt: str, default: bool = True) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    val = input(prompt + suffix + ": ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


def _test_es(host: str, user: str, password: str) -> bool:
    """Test Elasticsearch connection."""
    import base64
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    creds = base64.b64encode(f"{user}:{password}".encode()).decode()
    url = f"{host.rstrip('/')}/_cluster/health"
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"Basic {creds}")

    try:
        resp = urllib.request.urlopen(req, context=ctx, timeout=10)
        data = json.loads(resp.read().decode())
        print(f"  Connected! Cluster: {data.get('cluster_name', '?')}, status: {data.get('status', '?')}")
        return True
    except Exception as exc:
        print(f"  Connection failed: {exc}")
        return False


def _discover_indices(host: str, user: str, password: str) -> dict:
    """Try to auto-discover SO data streams."""
    import base64
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    creds = base64.b64encode(f"{user}:{password}".encode()).decode()
    url = f"{host.rstrip('/')}/_data_stream/*so*"
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"Basic {creds}")

    defaults = {
        "suricata": "logs-suricata.alerts-so",
        "zeek": "logs-zeek-so",
        "detections": "logs-detections.alerts-so",
        "syslog": "logs-syslog-so",
    }

    try:
        resp = urllib.request.urlopen(req, context=ctx, timeout=10)
        data = json.loads(resp.read().decode())
        names = [ds["name"] for ds in data.get("data_streams", [])]
        if names:
            print(f"  Found {len(names)} data streams:")
            for n in sorted(names)[:15]:
                print(f"    - {n}")
            # Verify standard indices exist
            for key, idx in defaults.items():
                if idx in names:
                    print(f"  {key}: {idx} (confirmed)")
                else:
                    print(f"  {key}: {idx} (NOT FOUND — you may need to adjust)")
        return defaults
    except Exception as exc:
        print(f"  Index discovery failed: {exc}")
        print("  Using standard Security Onion defaults")
        return defaults


def _test_ollama(url: str) -> list[str]:
    """Test Ollama connection and return available models."""
    try:
        req = urllib.request.Request(f"{url.rstrip('/')}/api/tags")
        resp = urllib.request.urlopen(req, timeout=10)
        data = json.loads(resp.read().decode())
        models = [m["name"] for m in data.get("models", [])]
        if models:
            print(f"  Connected! {len(models)} model(s) available:")
            for m in models:
                print(f"    - {m}")
        else:
            print("  Connected but no models found. Pull one with: ollama pull qwen3:14b")
        return models
    except Exception as exc:
        print(f"  Connection failed: {exc}")
        return []


def _build_toml(cfg: dict) -> str:
    """Build config.toml content from collected config dict."""
    lines = [
        "# so-ops configuration — generated by 'so-ops init'",
        "# chmod 600 config.toml",
        "",
        "[elasticsearch]",
        f'host = "{cfg["es_host"]}"',
        f'user = "{cfg["es_user"]}"',
        f'password = "{cfg["es_password"]}"',
        "verify_ssl = false",
        "",
        "[elasticsearch.indices]",
        f'suricata = "{cfg["indices"]["suricata"]}"',
        f'zeek = "{cfg["indices"]["zeek"]}"',
        f'detections = "{cfg["indices"]["detections"]}"',
        f'syslog = "{cfg["indices"]["syslog"]}"',
        f'data_streams = "*so*"',
        "",
        "[ollama]",
        f'url = "{cfg["ollama_url"]}"',
        f'model = "{cfg["ollama_model"]}"',
        "",
    ]

    # Notifications
    for provider, pcfg in cfg.get("notifications", {}).items():
        lines.append(f"[notifications.{provider}]")
        for k, v in pcfg.items():
            if isinstance(v, bool):
                lines.append(f"{k} = {'true' if v else 'false'}")
            elif isinstance(v, int):
                lines.append(f"{k} = {v}")
            else:
                lines.append(f'{k} = "{v}"')
        lines.append("")

    lines.extend([
        "[paths]",
        f'data_dir = "{cfg.get("data_dir", "~/so-ops-data")}"',
        "",
        "[triage]",
        "lookback_hours = 24",
        "max_alerts_per_run = 500",
        "max_alerts_per_query = 2000",
        "max_batch_size = 50",
        "llm_temperature = 0.1",
        "",
        "[triage.auto_noise]",
        "signatures = [",
        '    "ET INFO Session Traversal Utilities for NAT (STUN Binding Request)",',
        '    "ET INFO Session Traversal Utilities for NAT (STUN Binding Response)",',
        '    "ET INFO Session Traversal Utilities for NAT (STUN Binding Request On Non-Standard High Port)",',
        '    "ET INFO Microsoft Connection Test",',
        "]",
        "",
        "[triage.escalation]",
        "minimum_medium = [",
        '    "ET SCAN", "ET EXPLOIT", "ET TROJAN", "ET MALWARE", "ET ATTACK",',
        '    "ET DOS", "ET SHELLCODE", "ET WEB_SERVER", "ET WEB_CLIENT",',
        '    "GPL EXPLOIT", "GPL SHELLCODE", "GPL ATTACK",',
        "]",
        "minimum_high = [",
        '    "ET TROJAN", "ET MALWARE", "ET EXPLOIT Known", "ET ATTACK",',
        '    "ET SHELLCODE", "GPL EXPLOIT",',
        "]",
        "",
        "[health]",
        "llm_temperature = 0.3",
        "",
    ])

    # Vulnscan targets
    targets = cfg.get("vulnscan_targets", ["192.168.0.0/24"])
    targets_str = ", ".join(f'"{t}"' for t in targets)
    lines.extend([
        "[vulnscan]",
        f"targets = [{targets_str}]",
        'nmap_bin = "/usr/bin/nmap"',
        'nmap_args = "-sV --script=vulners -T4 --open"',
        'nuclei_docker = "projectdiscovery/nuclei:latest"',
        'nuclei_severity = "medium,high,critical"',
        "",
    ])

    # Network
    lines.extend([
        "[network]",
        'internal_prefixes = ["192.168.", "10.", "172.16."]',
        "",
    ])

    for zone in cfg.get("zones", []):
        lines.extend([
            "[[network.zones]]",
            f'cidr = "{zone["cidr"]}"',
            f'name = "{zone["name"]}"',
            f'description = "{zone["description"]}"',
            "",
        ])

    return "\n".join(lines) + "\n"


def _generate_systemd_units(config_path: str, venv_bin: str, user: str) -> dict[str, str]:
    """Generate systemd service + timer content."""
    work_dir = str(Path(config_path).parent)
    units = {}

    for tool, calendar, desc_short, desc_timer, timeout in [
        ("triage", "*:0/15", "SO Alert Triage", "Run SO alert triage every 15 minutes", 600),
        ("health", "07:10:00", "SO Daily Health Check", "Run SO daily health check", 900),
    ]:
        units[f"so-{tool}.service"] = f"""[Unit]
Description={desc_short}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User={user}
ExecStart={venv_bin}/so-ops {tool}
WorkingDirectory={work_dir}
Environment=SO_OPS_CONFIG={config_path}
StandardOutput=journal
StandardError=journal
TimeoutStartSec={timeout}
"""
        units[f"so-{tool}.timer"] = f"""[Unit]
Description={desc_timer}

[Timer]
OnCalendar={calendar}
Persistent=true

[Install]
WantedBy=timers.target
"""

    # Vulnscan: nmap (Sunday 2 AM) + nuclei (Wednesday 2 AM)
    for scan_type, day in [("nmap", "Sun"), ("nuclei", "Wed")]:
        units[f"so-vulnscan-{scan_type}.service"] = f"""[Unit]
Description=SO Vulnerability Scan ({scan_type})
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User={user}
ExecStart={venv_bin}/so-ops scan --type {scan_type}
WorkingDirectory={work_dir}
Environment=SO_OPS_CONFIG={config_path}
StandardOutput=journal
StandardError=journal
TimeoutStartSec=7200
"""
        units[f"so-vulnscan-{scan_type}.timer"] = f"""[Unit]
Description=SO {scan_type} vulnerability scan ({day} 2AM)

[Timer]
OnCalendar={day} *-*-* 02:00:00
Persistent=true

[Install]
WantedBy=timers.target
"""

    return units


def run_init():
    """Interactive setup wizard."""
    print("=" * 60)
    print("  so-ops — Security Onion Operations Toolkit Setup")
    print("=" * 60)
    print()

    # 1. Config file location
    default_path = str(Path.cwd() / "config.toml")
    alt_path = str(Path.home() / ".config" / "so-ops" / "config.toml")
    print(f"Config will be written to one of:")
    print(f"  1. {default_path}")
    print(f"  2. {alt_path}")
    choice = _ask("Choose location (1 or 2)", "1")
    config_path = default_path if choice == "1" else alt_path

    if Path(config_path).exists():
        if not _ask_yn(f"{config_path} already exists. Overwrite?", default=False):
            print("Aborted.")
            sys.exit(0)

    cfg: dict = {}

    # 2. Elasticsearch
    print("\n--- Elasticsearch ---")
    cfg["es_host"] = _ask("Security Onion manager URL", "https://192.168.0.200:9200")
    cfg["es_user"] = _ask("ES username", "so_elastic")
    cfg["es_password"] = _ask("ES password")

    print("Testing connection...")
    if _test_es(cfg["es_host"], cfg["es_user"], cfg["es_password"]):
        print("Discovering indices...")
        cfg["indices"] = _discover_indices(cfg["es_host"], cfg["es_user"], cfg["es_password"])
    else:
        print("Skipping index discovery (connection failed)")
        cfg["indices"] = {
            "suricata": "logs-suricata.alerts-so",
            "zeek": "logs-zeek-so",
            "detections": "logs-detections.alerts-so",
            "syslog": "logs-syslog-so",
        }

    # 3. Ollama
    print("\n--- Ollama LLM ---")
    cfg["ollama_url"] = _ask("Ollama URL", "http://localhost:11434")
    print("Testing connection...")
    models = _test_ollama(cfg["ollama_url"])
    if models:
        print("Pick a model (enter number or name):")
        for i, m in enumerate(models, 1):
            print(f"  {i}. {m}")
        pick = _ask("Model", models[0])
        if pick.isdigit() and 1 <= int(pick) <= len(models):
            cfg["ollama_model"] = models[int(pick) - 1]
        else:
            cfg["ollama_model"] = pick
    else:
        cfg["ollama_model"] = _ask("Model name", "qwen3:14b")

    # 4. Notifications
    print("\n--- Notifications ---")
    print("Available providers: email, discord, slack, ntfy, gotify, sms, webhook")
    providers = _ask("Which providers? (comma-separated, or 'none')", "none")
    cfg["notifications"] = {}

    if providers.strip().lower() != "none":
        for prov in [p.strip().lower() for p in providers.split(",")]:
            print(f"\n  Configuring {prov}...")
            pcfg: dict = {"enabled": True}
            if prov == "email":
                pcfg["smtp_host"] = _ask("    SMTP host")
                pcfg["smtp_port"] = int(_ask("    SMTP port", "465"))
                pcfg["from_address"] = _ask("    From address")
                pcfg["password"] = _ask("    SMTP password")
                pcfg["to_address"] = _ask("    To address")
            elif prov == "sms":
                pcfg["twilio_account_sid"] = _ask("    Twilio Account SID")
                pcfg["twilio_auth_token"] = _ask("    Twilio Auth Token")
                pcfg["from_number"] = _ask("    From number (e.g. +15551234567)")
                pcfg["to_number"] = _ask("    To number")
            elif prov in ("discord", "slack"):
                pcfg["webhook_url"] = _ask("    Webhook URL")
            elif prov == "ntfy":
                pcfg["url"] = _ask("    ntfy server URL", "https://ntfy.sh")
                pcfg["topic"] = _ask("    Topic name")
            elif prov == "gotify":
                pcfg["url"] = _ask("    Gotify URL")
                pcfg["token"] = _ask("    App token")
            elif prov == "webhook":
                pcfg["url"] = _ask("    Webhook URL")
            cfg["notifications"][prov] = pcfg

    # 5. Network zones
    print("\n--- Network Zones ---")
    print("Define your monitored subnets (helps the LLM understand your network).")
    cfg["zones"] = []
    while True:
        cidr = _ask("Subnet CIDR (or 'done')", "done")
        if cidr.lower() == "done":
            break
        name = _ask("  Zone name (e.g. server LAN)")
        desc = _ask("  Description (e.g. Security Onion manager, servers)")
        cfg["zones"].append({"cidr": cidr, "name": name, "description": desc})

    # 6. Vulnscan targets
    print("\n--- Vulnerability Scanning ---")
    targets_str = _ask("Scan targets (comma-separated CIDRs)", "192.168.0.0/24")
    cfg["vulnscan_targets"] = [t.strip() for t in targets_str.split(",")]

    # 7. Data directory
    cfg["data_dir"] = _ask("Data directory", "~/so-ops-data")

    # 8. Write config
    print(f"\nWriting config to {config_path}...")
    config_dir = Path(config_path).parent
    config_dir.mkdir(parents=True, exist_ok=True)
    toml_content = _build_toml(cfg)
    Path(config_path).write_text(toml_content)
    os.chmod(config_path, 0o600)
    print(f"  Written! (permissions: 600)")

    # 9. Systemd timers (optional)
    print("\n--- Systemd Timers (optional) ---")
    if _ask_yn("Generate systemd service/timer files?", default=True):
        user = _ask("Linux username for services", os.environ.get("USER", "om"))
        venv_bin = _ask("Path to venv bin dir", str(Path(config_path).parent / ".venv" / "bin"))

        units = _generate_systemd_units(config_path, venv_bin, user)
        systemd_dir = Path(config_path).parent / "systemd"
        systemd_dir.mkdir(exist_ok=True)

        for filename, content in units.items():
            (systemd_dir / filename).write_text(content)
            print(f"  Wrote {systemd_dir / filename}")

        print("\n  To install timers:")
        print(f"    sudo cp {systemd_dir}/*.service {systemd_dir}/*.timer /etc/systemd/system/")
        print("    sudo systemctl daemon-reload")
        print("    sudo systemctl enable --now so-triage.timer so-health.timer")
        print("    sudo systemctl enable --now so-vulnscan-nmap.timer so-vulnscan-nuclei.timer")

    # 10. Validate
    print("\n--- Validating config ---")
    try:
        from so_ops.config import load_config
        load_config(Path(config_path))
        print("  Config loaded successfully!")
    except SystemExit:
        print("  Config validation failed — check the file and fix errors.")
        sys.exit(1)

    print("\n" + "=" * 60)
    print("  Setup complete! Next steps:")
    print(f"    so-ops config-check        # verify config")
    print(f"    so-ops test-notify          # test notifications")
    print(f"    so-ops triage --dry-run     # test triage (no LLM)")
    print(f"    so-ops health               # run health check")
    print("=" * 60)
